// Generated by Framer Code, do not edit manually
import type * as React from 'react'

/**
 * Props are named after your Framer control titles. The original hashed
 * control ids (e.g. "b00pKBnWz") are also accepted at runtime; when both a
 * readable name and its hashed id are passed, the hashed value wins.
 */
export interface ProjectCardProps {
  variant?: 'Project Thumbnail' | 'Hero' | 'Phone' | 'Empty State'; // Variant
  mainImage?: {src: string, srcSet?: string, alt?: string}; // Main Image
  title?: string; // Title
  onV3EdlvBkGChange?: any;
  typeOfWork?: string; // Type of work
  oniloSRMXnRChange?: any;
  projectLink?: string; // Project Link
  cursor?: any; // Cursor
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  id?: string;
  ref?: React.Ref<HTMLElement>;
  width?: number | string;
  height?: number | string;
  layoutId?: string;
  locale?: string;
}

export interface ProjectCardResponsiveProps extends Omit<ProjectCardProps, 'variant'> {
  variants?: Partial<Record<'base' | 'sm' | 'md' | 'lg' | 'xl' | '2xl', ProjectCardProps['variant']>> & { base: ProjectCardProps['variant'] }
}

declare const ProjectCard: React.ComponentType<ProjectCardProps> & {
  Responsive: React.ComponentType<ProjectCardResponsiveProps>
}

export default ProjectCard
