// @ts-nocheck
/* eslint-disable */
/* Generated by Framer Code, do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Project Thumbnail' | 'Hero' | 'Phone' | 'Empty State' // Variant
 * mainImage?: {src: string, srcSet?: string, alt?: string} // Main Image
 * title?: string // Title
 * onV3EdlvBkGChange?: any // onV3EdlvBkGChange
 * typeOfWork?: string // Type of work
 * oniloSRMXnRChange?: any // oniloSRMXnRChange
 * projectLink?: string // Project Link
 * cursor?: any // Cursor
}} Props

 */
var __fcWindow = typeof window !== "undefined" ? window : undefined;
var __fcNavigator = typeof __fcWindow !== "undefined" ? navigator : undefined;

// virtual:project-card
import { jsx } from "react/jsx-runtime";
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "framercode";
import * as React from "react";
import { forwardRef } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13 14 L 17 14 C 17.552 14 18 13.552 18 13 L 18 12 C 18 10.343 16.657 9 15 9 L 13 9 M 10.764 5 C 11.593 5.927 12.909 6.246 14.071 5.803 C 15.233 5.359 16 4.244 16 3 C 16 1.756 15.233 0.641 14.071 0.198 C 12.909 -0.246 11.593 0.073 10.764 1 M 0 13 L 0 12 C 0 10.343 1.343 9 3 9 L 7 9 C 8.657 9 10 10.343 10 12 L 10 13 C 10 13.552 9.552 14 9 14 L 1 14 C 0.448 14 0 13.552 0 13 Z M 8 3 C 8 4.657 6.657 6 5 6 C 3.343 6 2 4.657 2 3 C 2 1.343 3.343 0 5 0 C 6.657 0 8 1.343 8 3 Z" fill="transparent" height="14.000126838684082px" id="TyV95yvIi" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--1dlwa4q, 2)" stroke="var(--1hdsue, black)" transform="translate(3 5)" width="18px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		sBw9NzqkQ: width1 ?? props.sBw9NzqkQ ?? 2,
		yG6t3qT1h: color ?? props.yG6t3qT1h ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		sBw9NzqkQ,
		yG6t3qT1h,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("1705439008", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-oOX7M", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1dlwa4q": sBw9NzqkQ,
				"--1hdsue": yG6t3qT1h,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css = [
	`.framer-oOX7M { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-oOX7M");
Icon.displayName = "Users";
var EYGvdN6UD_default = Icon;
addPropertyControls(Icon, {
	sBw9NzqkQ: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 4,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
	yG6t3qT1h: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
});
var __FramerMetadata__ = {
	exports: {
		default: {
			type: "reactComponent",
			name: "Icon",
			slots: [],
			annotations: {
				framerIntrinsicHeight: "24",
				framerIntrinsicWidth: "24",
				framerSupportedLayoutWidth: "any-prefer-fixed",
				framerVariables: '{"sBw9NzqkQ":"width1","yG6t3qT1h":"color"}',
				framerImmutableVariables: "true",
				framerVector:
					'{"name":"Users","color":{"type":"variable","value":"1hdsue"},"set":{"localId":"vectorSet/gFyVYCRbC","id":"gFyVYCRbC","moduleId":"2BtL64EofggzGo2O20Ku"}}',
				framerSupportedLayoutHeight: "any-prefer-fixed",
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { fontStore } from "framercode";
fontStore.loadFonts([
	"FS;Switzer-medium",
	"FS;Switzer-semibold",
	"FS;Switzer-semibold italic",
	"FS;Switzer-medium italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Switzer",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/OYB4CXKJQXKTNSLJMTDQOIVUL2V5EL7S/WYO2P7DQVV5RNXGMCUO2HL4RJP4VFUAS/6XPIMU23OJVRY676OG5YVJMWEHWICATX.woff2",
				weight: "500",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/5SZVFDB7V52TI6ULVC6J3WQZQCIZVDV5/ODYPSTCUDMKSTYIPTV4CLQ7URIK7XYBJ/YS3VPNVO4B3TOJMEXDGFZQ4TLZGGSRZC.woff2",
				weight: "600",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2UC2M25RQ2XRSGCBJRQ2G5SNXCROECQB/QJT3T33NN372363FJY5EO5D63GKDKLDK/IOAFMDAPNX3S6OL2GYQQJ2FFJIRSVB3N.woff2",
				weight: "600",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/QMRBNVYKDJEZ66DA22SPWH5EVVYACHCU/ZHMXHHA546NDNEHJN5RPZX5KISJY5CWF/C6VLICDGQWYKV6YT65TM5G3OVN4AOZBN.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	'.framer-FNn37 .framer-styles-preset-1igwnwn:not(.rich-text-wrapper), .framer-FNn37 .framer-styles-preset-1igwnwn.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 600; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 32px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 992px) { .framer-FNn37 .framer-styles-preset-1igwnwn:not(.rich-text-wrapper), .framer-FNn37 .framer-styles-preset-1igwnwn.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 600; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 32px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 991px) and (min-width: 768px) { .framer-FNn37 .framer-styles-preset-1igwnwn:not(.rich-text-wrapper), .framer-FNn37 .framer-styles-preset-1igwnwn.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 600; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 32px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 767px) and (min-width: 0px) { .framer-FNn37 .framer-styles-preset-1igwnwn:not(.rich-text-wrapper), .framer-FNn37 .framer-styles-preset-1igwnwn.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 600; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 140%; --framer-paragraph-spacing: 32px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-FNn37";
var __FramerMetadata__2 = {
	exports: {
		className: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		fonts: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		css: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { fontStore as fontStore2 } from "framercode";
fontStore2.loadFonts([
	"FS;Switzer-semibold",
	"FS;Switzer-black",
	"FS;Switzer-black italic",
	"FS;Switzer-semibold italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Switzer",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Switzer",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/5SZVFDB7V52TI6ULVC6J3WQZQCIZVDV5/ODYPSTCUDMKSTYIPTV4CLQ7URIK7XYBJ/YS3VPNVO4B3TOJMEXDGFZQ4TLZGGSRZC.woff2",
				weight: "600",
			},
			{
				cssFamilyName: "Switzer",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Switzer",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/A54N3N7J5AY6YOPYJKLHF5VH7G7HSSUN/ERWIWIB434FMFHQFSSBD233EP3C62HOI/TOHQHMLIEIPKVF2JPM6SVKXFYGO5G2TJ.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Switzer",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Switzer",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/FQHNKZEV35SAMFWVFCFSORJXUNHNILL4/X4YCR4COAQTK5XB6JCDDBS7Q33AQWUAE/J7XVDQ2IJENINPUAVBDJNH3VEXVDSPQQ.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Switzer",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Switzer",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2UC2M25RQ2XRSGCBJRQ2G5SNXCROECQB/QJT3T33NN372363FJY5EO5D63GKDKLDK/IOAFMDAPNX3S6OL2GYQQJ2FFJIRSVB3N.woff2",
				weight: "600",
			},
		],
	},
];
var css3 = [
	'.framer-P6rHN .framer-styles-preset-455vy9:not(.rich-text-wrapper), .framer-P6rHN .framer-styles-preset-455vy9.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 112%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 992px) { .framer-P6rHN .framer-styles-preset-455vy9:not(.rich-text-wrapper), .framer-P6rHN .framer-styles-preset-455vy9.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 112%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 991px) and (min-width: 768px) { .framer-P6rHN .framer-styles-preset-455vy9:not(.rich-text-wrapper), .framer-P6rHN .framer-styles-preset-455vy9.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 112%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 767px) and (min-width: 0px) { .framer-P6rHN .framer-styles-preset-455vy9:not(.rich-text-wrapper), .framer-P6rHN .framer-styles-preset-455vy9.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.02em; --framer-line-height: 112%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-P6rHN";
var __FramerMetadata__3 = {
	exports: {
		className: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		fonts: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		css: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	withCSS as withCSS2,
} from "framercode";
import * as React2 from "react";
import { forwardRef as forwardRef3 } from "react";
var mask2 = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 10 L 10 0" fill="transparent" height="10px" id="Gm6ErcvSs" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(7 7)" width="10px"/><path d="M 0 0 L 10 0 L 10 10" fill="transparent" height="10px" id="TScaaNOIP" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(7 7)" width="10px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG2 = /* @__PURE__ */ forwardRef3((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		/>
	) : (
		<div suppressHydrationWarning={true} {...rest} ref={ref} />
	);
});
var getProps2 = ({ height, id, stroke, width, ...props }) => {
	return {
		...props,
		UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		UO5clYVeQ,
		...restProps
	} = getProps2(props);
	return (
		<SVG2
			suppressHydrationWarning={true}
			{...restProps}
			className={cx2("framer-r0AVb", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--43q7um": UO5clYVeQ,
				...style,
			}}
		/>
	);
});
var css4 = [
	`.framer-r0AVb { -webkit-mask: ${mask2}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css4, "framer-r0AVb");
Icon2.displayName = "Arrow Up Right";
var X5rbDZv9v_default = Icon2;
addPropertyControls2(Icon2, {
	UO5clYVeQ: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Stroke",
		type: ControlType2.Color,
	},
});
var __FramerMetadata__4 = {
	exports: {
		default: {
			type: "reactComponent",
			name: "Icon",
			slots: [],
			annotations: {
				framerIntrinsicHeight: "24",
				framerDisableUnlink: "true",
				framerSupportedLayoutHeight: "any-prefer-fixed",
				framerVariables: '{"UO5clYVeQ":"stroke"}',
				framerVector:
					'{"name":"Arrow Up Right","color":{"type":"variable","value":"43q7um"},"set":{"localId":"vectorSet/T8qKXkLfy","id":"T8qKXkLfy","moduleId":"fiHEoJwBMFnT6QLOcpPz"}}',
				framerSupportedLayoutWidth: "any-prefer-fixed",
				framerImmutableVariables: "true",
				framerContractVersion: "1",
				framerIntrinsicWidth: "24",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS3,
} from "framercode";
import {
	LayoutGroup,
	motion as motion3,
	MotionConfigContext,
} from "framercode";
import * as React3 from "react";
import { useRef } from "react";
var ArrowUpRightFonts = getFonts(X5rbDZv9v_default);
var cycleOrder = ["NwqAfOsnO", "yaT7O5nxk"];
var serializationHash = "framer-uVSJt";
var variantClassNames = {
	NwqAfOsnO: "framer-v-r5zzir",
	yaT7O5nxk: "framer-v-1e1y90c",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var humanReadableVariantMap = {
	Default: "NwqAfOsnO",
	Hover: "yaT7O5nxk",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NwqAfOsnO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NwqAfOsnO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion3.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-r5zzir",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"NwqAfOsnO"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								yaT7O5nxk: {
									"data-framer-name": "Hover",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<X5rbDZv9v_default
							suppressHydrationWarning={true}
							animated={true}
							className={"framer-1m392vo"}
							layoutDependency={layoutDependency}
							layoutId={"fzQdWHJ44"}
							style={{
								"--43q7um":
									"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
							}}
						/>
						<X5rbDZv9v_default
							suppressHydrationWarning={true}
							animated={true}
							className={"framer-b3gi0s"}
							layoutDependency={layoutDependency}
							layoutId={"ug4PuTTvJ"}
							style={{
								"--43q7um":
									"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
							}}
						/>
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uVSJt.framer-10k7if2, .framer-uVSJt .framer-10k7if2 { display: block; }",
	".framer-uVSJt.framer-r5zzir { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-uVSJt .framer-1m392vo { flex: none; height: var(--framer-aspect-ratio-supported, 18px); position: relative; width: 18px; z-index: 1; }",
	".framer-uVSJt .framer-b3gi0s { bottom: -16px; flex: none; height: var(--framer-aspect-ratio-supported, 18px); left: -16px; position: absolute; width: 18px; z-index: 1; }",
	".framer-uVSJt.framer-v-1e1y90c .framer-1m392vo { position: absolute; right: -16px; top: -16px; }",
	".framer-uVSJt.framer-v-1e1y90c .framer-b3gi0s { bottom: unset; left: unset; position: relative; }",
];
var Framerm2xQ4XX2C = withCSS3(Component3, css5, "framer-uVSJt");
var m2xQ4XX2C_default = Framerm2xQ4XX2C;
Framerm2xQ4XX2C.displayName = "Arrow Icon";
Framerm2xQ4XX2C.defaultProps = {
	height: 18,
	width: 18,
};
addPropertyControls3(Framerm2xQ4XX2C, {
	variant: {
		options: ["NwqAfOsnO", "yaT7O5nxk"],
		optionTitles: ["Default", "Hover"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts(
	Framerm2xQ4XX2C,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ArrowUpRightFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
var __FramerMetadata__5 = {
	exports: {
		Props: {
			type: "tsType",
			annotations: {
				framerContractVersion: "1",
			},
		},
		default: {
			type: "reactComponent",
			name: "Framerm2xQ4XX2C",
			slots: [],
			annotations: {
				framerColorSyntax: "true",
				framerCanvasComponentVariantDetails:
					'{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"yaT7O5nxk":{"layout":["auto","auto"]}}}',
				framerImmutableVariables: "true",
				framerComponentViewportWidth: "true",
				framerIntrinsicHeight: "18",
				framerDisplayContentsDiv: "false",
				framerAutoSizeImages: "true",
				framerContractVersion: "1",
				framerIntrinsicWidth: "18",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { jsx as _jsx4, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls4,
	ComponentViewportProvider,
	ControlType as ControlType4,
	cx as cx4,
	forwardLoader,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	Link,
	RichText,
	runTasksWithYield,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS4,
} from "framercode";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion4,
	MotionConfigContext as MotionConfigContext2,
} from "framercode";
import * as React4 from "react";
import { useRef as useRef2 } from "react";
var UsersFonts = getFonts2(EYGvdN6UD_default);
var ArrowIconFonts = getFonts2(m2xQ4XX2C_default);
var enabledGestures = {
	zhYui7icB: {
		hover: true,
	},
};
var cycleOrder2 = ["zhYui7icB", "xReGGV0wD", "W6fmImdIS", "lShzS9jb1"];
var serializationHash2 = "framer-6T73V";
var variantClassNames2 = {
	lShzS9jb1: "framer-v-lakwe4",
	W6fmImdIS: "framer-v-x9rc57",
	xReGGV0wD: "framer-v-1e0bdqz",
	zhYui7icB: "framer-v-1p135ve",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var LGYqcgIu1 = void 0;
var UHrBTw6mM = void 0;
var z6ovJ6t8Z = void 0;
var V3EdlvBkG = void 0;
var iloSRMXnR = void 0;
var transition12 = {
	delay: 0,
	duration: 0.6,
	ease: [0.68, 0, 0.22, 0.83],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	"Empty State": "lShzS9jb1",
	"Project Thumbnail": "zhYui7icB",
	Hero: "xReGGV0wD",
	Phone: "W6fmImdIS",
};
var Variants2 = motion4.create(React4.Fragment);
var getProps4 = ({
	cursor,
	height,
	id,
	mainImage,
	projectLink,
	title,
	typeOfWork,
	width,
	...props
}) => {
	return {
		...props,
		iloSRMXnR: typeOfWork ?? props.iloSRMXnR ?? "Branding / Ecommerce",
		LGYqcgIu1: cursor ?? props.LGYqcgIu1,
		UHrBTw6mM: projectLink ?? props.UHrBTw6mM,
		V3EdlvBkG: title ?? props.V3EdlvBkG ?? "Project Name",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "zhYui7icB",
		z6ovJ6t8Z: mainImage ?? props.z6ovJ6t8Z,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		z6ovJ6t8Z: z6ovJ6t8Z2,
		V3EdlvBkG: V3EdlvBkG2,
		iloSRMXnR: iloSRMXnR2,
		UHrBTw6mM: UHrBTw6mM2,
		LGYqcgIu1: LGYqcgIu12,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "zhYui7icB",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx4(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "lShzS9jb1") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "lShzS9jb1") return false;
		return true;
	};
	return (
		<LayoutGroup2
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants2
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition2 suppressHydrationWarning={true} value={transition12}>
					<Link
						suppressHydrationWarning={true}
						href={UHrBTw6mM2}
						motionChild={true}
						nodeId={"zhYui7icB"}
						scopeId={"rUZIxkN3p"}
						{...addPropertyOverrides2(
							{
								lShzS9jb1: {
									href: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion4.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx4(scopingClassNames, "framer-1p135ve", className3, classNames)} framer-17f1mt2`}
							data-framer-cursor={LGYqcgIu12}
							data-framer-name={"Project Thumbnail"}
							layoutDependency={layoutDependency}
							layoutId={"zhYui7icB"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								boxShadow: "none",
								...style,
							}}
							variants={{
								"zhYui7icB-hover": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
									boxShadow: "none",
								},
								lShzS9jb1: {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-e3a90888-763b-420f-bb27-f2520e07d9b1, rgb(222, 222, 222))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgb(255, 255, 255)",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
									boxShadow:
										"0px 0.5971439051427296px 0.5971439051427296px -0.9375px rgba(0, 0, 0, 0.07), 0px 1.8108796073283884px 1.8108796073283884px -1.875px rgba(0, 0, 0, 0.07), 0px 4.786990141113346px 4.786990141113346px -2.8125px rgba(0, 0, 0, 0.06), 0px 15px 15px -3.75px rgba(0, 0, 0, 0.03)",
								},
							}}
							{...addPropertyOverrides2(
								{
									lShzS9jb1: {
										"data-border": true,
										"data-framer-cursor": void 0,
										"data-framer-name": "Empty State",
									},
									W6fmImdIS: {
										"data-framer-name": "Phone",
									},
									xReGGV0wD: {
										"data-framer-cursor": void 0,
										"data-framer-name": "Hero",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion4.div
								suppressHydrationWarning={true}
								className={"framer-mdi5qa"}
								data-framer-name={"Image Container"}
								layoutDependency={layoutDependency}
								layoutId={"gpOJStwxR"}
								style={{
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								{isDisplayed() && (
									<motion4.div
										suppressHydrationWarning={true}
										className={"framer-1k6o7jk"}
										data-framer-name={"Empty State"}
										layoutDependency={layoutDependency}
										layoutId={"vu3bC9DZ7"}
									>
										<motion4.div
											suppressHydrationWarning={true}
											className={"framer-2u1irp"}
											data-border={true}
											data-framer-name={"Icon"}
											layoutDependency={layoutDependency}
											layoutId={"sHYAHFjCL"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-e3a90888-763b-420f-bb27-f2520e07d9b1, rgb(222, 222, 222))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-bf8bd38a-4575-40c0-9459-6a86668113f1, rgb(250, 250, 250))",
												borderBottomLeftRadius: 8,
												borderBottomRightRadius: 8,
												borderTopLeftRadius: 8,
												borderTopRightRadius: 8,
												boxShadow:
													"inset 0px 2px 4px 0px rgba(255, 255, 255, 0.4), 0px 0.7409732186279143px 0.7409732186279143px -0.75px rgba(0, 0, 0, 0.07), 0px 2.0178668455264415px 2.0178668455264415px -1.5px rgba(0, 0, 0, 0.07), 0px 4.430505261661892px 4.430505261661892px -2.25px rgba(0, 0, 0, 0.07), 0px 9.834710084098335px 9.834710084098335px -3px rgba(0, 0, 0, 0.06), 0px 25px 25px -3.75px rgba(0, 0, 0, 0.03), 0px 0px 0px 1px var(--token-08cb0f10-6dc5-4949-913f-dbd7168f1cf0, rgb(240, 240, 240))",
											}}
										>
											<EYGvdN6UD_default
												suppressHydrationWarning={true}
												animated={true}
												className={"framer-ggjqzy"}
												layoutDependency={layoutDependency}
												layoutId={"jdjlo1Q1Z"}
												style={{
													"--1dlwa4q": 2,
													"--1hdsue": "rgb(0, 0, 0)",
												}}
											/>
										</motion4.div>
										<motion4.div
											suppressHydrationWarning={true}
											className={"framer-1v2tubw"}
											data-framer-name={"Text"}
											layoutDependency={layoutDependency}
											layoutId={"OWQ4Coi2T"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-ud8vro"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"tF8Ib82Op"}
												style={{
													"--extracted-1w3ko1f":
														"var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))",
													"--extracted-r6o4lv":
														"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React4.Fragment>
													<motion4.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1igwnwn"}
														data-styles-preset={"Sz9S4_GWH"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0)))",
														}}
													>
														<motion4.span
															suppressHydrationWarning={true}
															style={{
																"--framer-text-color":
																	"var(--extracted-1w3ko1f, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))",
															}}
														>
															{"Got a cool idea?"}
														</motion4.span>
														{" This spot is waiting for your success story."}
													</motion4.p>
												</React4.Fragment>
											</RichText>
										</motion4.div>
									</motion4.div>
								)}
								{isDisplayed1() && (
									<Image1
										suppressHydrationWarning={true}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0 + 0,
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(z6ovJ6t8Z2),
										}}
										className={"framer-13gjxaf"}
										layoutDependency={layoutDependency}
										layoutId={"S5H5hPPW3"}
										style={{
											scale: 1,
										}}
										variants={{
											"zhYui7icB-hover": {
												scale: 1.1,
											},
										}}
									/>
								)}
							</motion4.div>
							{isDisplayed1() && (
								<motion4.div
									suppressHydrationWarning={true}
									className={"framer-15eyyj4"}
									data-framer-name={"Project Client / View Project"}
									layoutDependency={layoutDependency}
									layoutId={"kS8nMCvyR"}
									style={{
										opacity: 1,
									}}
									variants={{
										"zhYui7icB-hover": {
											opacity: 1,
										},
										W6fmImdIS: {
											opacity: 1,
										},
										xReGGV0wD: {
											opacity: 0,
										},
									}}
									{...addPropertyOverrides2(
										{
											xReGGV0wD: {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion4.div
										suppressHydrationWarning={true}
										className={"framer-11z3dnp"}
										layoutDependency={layoutDependency}
										layoutId={"xROv5lpgq"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-letzu0"}
											data-framer-name={"Project Name"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"mc9JRinwK"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={V3EdlvBkG2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1igwnwn"}
													data-styles-preset={"Sz9S4_GWH"}
													dir={"auto"}
												>
													{"Project Name"}
												</motion4.p>
											</React4.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-9237n6"}
											data-framer-name={"Type of Work"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"JO5kMMtZ5"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={iloSRMXnR2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-455vy9"}
													data-styles-preset={"xYEC_wF3E"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))",
													}}
												>
													{"Branding / Ecommerce"}
												</motion4.p>
											</React4.Fragment>
										</RichText>
									</motion4.div>
									<motion4.div
										suppressHydrationWarning={true}
										className={"framer-1d1mk6y"}
										data-framer-name={"View Project"}
										layoutDependency={layoutDependency}
										layoutId={"Ho0v9kqRz"}
									>
										<ComponentViewportProvider
											suppressHydrationWarning={true}
											height={18}
											y={(componentViewport?.y || 0) + 0 + 312 + 12.32 + 0}
											{...addPropertyOverrides2(
												{
													xReGGV0wD: {
														y:
															(componentViewport?.y || 0) +
															(componentViewport?.height || 200) -
															42.64 +
															12.32 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-1wq9qts-container"}
												layoutDependency={layoutDependency}
												layoutId={"xoHFEpRkY-container"}
												nodeId={"xoHFEpRkY"}
												rendersWithMotion={true}
												scopeId={"rUZIxkN3p"}
												style={{
													opacity: 0.6,
												}}
											>
												{
													/* @__PURE__ */ _jsx4(m2xQ4XX2C_default, {
														suppressHydrationWarning: true,
														height: "100%",
														id: "xoHFEpRkY",
														layoutId: "xoHFEpRkY",
														variant: matchVariant("NwqAfOsnO"),
														width: "100%",
														...addPropertyOverrides2(
															{
																"zhYui7icB-hover": {
																	variant: matchVariant("yaT7O5nxk"),
																},
															},
															baseVariant,
															gestureVariant,
														),
													})
												}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-x1vmqm"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"bISPUMTY9"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-455vy9"}
													data-styles-preset={"xYEC_wF3E"}
													dir={"auto"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))",
													}}
												>
													{"View Project"}
												</motion4.p>
											</React4.Fragment>
										</RichText>
									</motion4.div>
								</motion4.div>
							)}
						</motion4.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	".framer-6T73V.framer-17f1mt2, .framer-6T73V .framer-17f1mt2 { display: block; }",
	".framer-6T73V.framer-1p135ve { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 400px; }",
	".framer-6T73V .framer-mdi5qa { align-content: center; align-items: center; aspect-ratio: 1.3333333333333333 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: auto; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-6T73V .framer-1k6o7jk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 32px; position: relative; width: 1px; }",
	".framer-6T73V .framer-2u1irp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-6T73V .framer-ggjqzy { flex: none; height: auto; position: relative; width: 24px; }",
	".framer-6T73V .framer-1v2tubw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-6T73V .framer-ud8vro { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-6T73V .framer-13gjxaf { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-6T73V .framer-15eyyj4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-6T73V .framer-11z3dnp { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-6T73V .framer-letzu0, .framer-6T73V .framer-9237n6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-6T73V .framer-1d1mk6y { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-6T73V .framer-1wq9qts-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-6T73V .framer-x1vmqm { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-6T73V.framer-v-1e0bdqz.framer-1p135ve, .framer-6T73V.framer-v-x9rc57.framer-1p135ve, .framer-6T73V.framer-v-lakwe4.framer-1p135ve { cursor: unset; }",
	".framer-6T73V.framer-v-1e0bdqz .framer-15eyyj4 { bottom: 0px; left: 50%; position: absolute; }",
	".framer-6T73V.framer-v-1p135ve.hover .framer-15eyyj4 { mix-blend-mode: exclusion; }",
	".framer-6T73V.framer-v-1p135ve.hover .framer-1d1mk6y { z-index: 1; }",
	...css2,
	...css3,
	'.framer-6T73V[data-border="true"]::after, .framer-6T73V [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerrUZIxkN3p = withCSS4(Component4, css6, "framer-6T73V");
var rUZIxkN3p_default = FramerrUZIxkN3p;
FramerrUZIxkN3p.displayName = "Project Card";
FramerrUZIxkN3p.defaultProps = {
	height: 354,
	width: 400,
};
addPropertyControls4(FramerrUZIxkN3p, {
	variant: {
		options: ["zhYui7icB", "xReGGV0wD", "W6fmImdIS", "lShzS9jb1"],
		optionTitles: ["Project Thumbnail", "Hero", "Phone", "Empty State"],
		title: "Variant",
		type: ControlType4.Enum,
	},
	z6ovJ6t8Z: {
		title: "Main Image",
		type: ControlType4.ResponsiveImage,
	},
	V3EdlvBkG: {
		defaultValue: "Project Name",
		displayTextArea: false,
		title: "Title",
		type: ControlType4.String,
	},
	onV3EdlvBkGChange: {
		changes: "V3EdlvBkG",
		type: ControlType4.ChangeHandler,
	},
	iloSRMXnR: {
		defaultValue: "Branding / Ecommerce",
		displayTextArea: false,
		title: "Type of work",
		type: ControlType4.String,
	},
	oniloSRMXnRChange: {
		changes: "iloSRMXnR",
		type: ControlType4.ChangeHandler,
	},
	UHrBTw6mM: {
		title: "Project Link",
		type: ControlType4.Link,
	},
	LGYqcgIu1: {
		title: "Cursor",
		type: ControlType4.CustomCursor,
	},
});
addFonts2(
	FramerrUZIxkN3p,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...UsersFonts,
		...ArrowIconFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerrUZIxkN3p.loader = {
	load: (props, context) => {
		return runTasksWithYield(
			[() => forwardLoader(m2xQ4XX2C_default, {}, context)],
			context,
		);
	},
};
var __FramerMetadata__6 = {
	exports: {
		default: {
			type: "reactComponent",
			name: "FramerrUZIxkN3p",
			slots: [],
			annotations: {
				framerAutoSizeImages: "true",
				framerIntrinsicHeight: "354",
				framerVariables:
					'{"z6ovJ6t8Z":"mainImage","V3EdlvBkG":"title","iloSRMXnR":"typeOfWork","UHrBTw6mM":"projectLink","LGYqcgIu1":"cursor"}',
				framerComponentViewportWidth: "true",
				framerCanvasComponentVariantDetails:
					'{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"xReGGV0wD":{"layout":["fixed","auto"]},"W6fmImdIS":{"layout":["fixed","auto"]},"lShzS9jb1":{"layout":["fixed","auto"]},"dWQU2G7tX":{"layout":["fixed","auto"]}}}',
				framerImmutableVariables: "true",
				framerIntrinsicWidth: "400",
				framerContractVersion: "1",
				framerDisplayContentsDiv: "false",
				framerColorSyntax: "true",
			},
		},
		Props: {
			type: "tsType",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};

// virtual:__routes
var routes = {
	augiA20Il: {
		path: "/",
	},
	O37Bzv5zI: {
		path: "/projects/:slug",
	},
	mWs3HA33o: {
		path: "/404",
	},
	f7m8jEuds: {
		path: "/terms",
	},
	XFi_Ib9jj: {
		path: "/privacy-policy",
	},
	Gwh88uPT2: {
		path: "/:slug",
	},
	zXoIvBUbO: {
		path: "/blog/:slug",
	},
	O7vceP692: {
		path: "/blog",
	},
	eOPu6CN6f: {
		path: "/projects",
	},
	iAbASwpMq: {
		path: "/design-system",
	},
};

// virtual:project-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "framercode";
import { WithFramerBreakpoints } from "framercode";
var locales = [];
var defaultResponsiveVariants = {
	base: "W6fmImdIS",
};
var __fcPropMap = {
	mainImage: "z6ovJ6t8Z",
	title: "V3EdlvBkG",
	typeOfWork: "iloSRMXnR",
	projectLink: "UHrBTw6mM",
	cursor: "LGYqcgIu1",
};
function __fcProps(props) {
	const out = {
		...props,
	};
	for (const [readable, hashed] of Object.entries(__fcPropMap)) {
		if (readable in out) {
			if (!(hashed in out)) out[hashed] = out[readable];
			delete out[readable];
		}
	}
	return out;
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"ec8a9ed824861f4293bff469a14d5d70bf05d49f88f4646410888070b973ac27"
			}
			locale={locale}
			locales={locales}
		>
			{
				/* @__PURE__ */ jsx(rUZIxkN3p_default, {
					suppressHydrationWarning: true,
					...__fcProps(rest),
				})
			}
		</ContextProviders>
	);
}
/**
 * @type {import("framercode").Breakpoint}
 * Represents a responsive breakpoint for framercode.
 */

/**
 * @typedef VariantsMap
 * Partial record of Breakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in Breakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"ec8a9ed824861f4293bff469a14d5d70bf05d49f88f4646410888070b973ac27"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={rUZIxkN3p_default}
				variants={defaultResponsiveVariants}
				{...__fcProps(rest)}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, rUZIxkN3p_default);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
