/* Generated by Framer Code, do not edit manually */
import './framercode/styles.css'
import ProjectCardFramerComponent from './framercode/project-card'

export default function App() {
  return (
    <div className='flex flex-col items-center gap-3 bg-[rgb(255,_255,_255)]'>
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
      />
      <ProjectCardFramerComponent.Responsive
        title={"Mugen Studio"}
        typeOfWork={"Branding / Web"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        title={"KYMA"}
        typeOfWork={"Web Design"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        title={"Mugen Studio"}
        typeOfWork={"Branding / Web"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        title={"KYMA"}
        typeOfWork={"Web Design"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        title={"Mugen Studio"}
        typeOfWork={"Branding / Web"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        title={"KYMA"}
        typeOfWork={"Web Design"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Kora"}
        typeOfWork={"Consulting Site"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"KYMA"}
        typeOfWork={"AI Agency"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Mugen"}
        typeOfWork={"Design studio"}
        mainImage={{ src: "https://framerusercontent.com/images/AZe7hFsRlGAWp9spF25RMEwS0gA.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Axiom"}
        typeOfWork={"Ecommerce Site"}
        mainImage={{ src: "https://framerusercontent.com/images/q3ruKmoVYmFXP9EeyZlQPnTDuVw.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Kora"}
        typeOfWork={"Consulting Site"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"KYMA"}
        typeOfWork={"AI Agency"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Mugen"}
        typeOfWork={"Design studio"}
        mainImage={{ src: "https://framerusercontent.com/images/AZe7hFsRlGAWp9spF25RMEwS0gA.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Axiom"}
        typeOfWork={"Ecommerce Site"}
        mainImage={{ src: "https://framerusercontent.com/images/q3ruKmoVYmFXP9EeyZlQPnTDuVw.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Kora"}
        typeOfWork={"Consulting Site"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"KYMA"}
        typeOfWork={"AI Agency"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Mugen"}
        typeOfWork={"Design studio"}
        mainImage={{ src: "https://framerusercontent.com/images/AZe7hFsRlGAWp9spF25RMEwS0gA.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Axiom"}
        typeOfWork={"Ecommerce Site"}
        mainImage={{ src: "https://framerusercontent.com/images/q3ruKmoVYmFXP9EeyZlQPnTDuVw.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Kora"}
        typeOfWork={"Consulting Site"}
        mainImage={{ src: "https://framerusercontent.com/images/wn56GiYIGN9okbMTZQ8fV2UQ0.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"KYMA"}
        typeOfWork={"AI Agency"}
        mainImage={{ src: "https://framerusercontent.com/images/tBF8hMQFxONWA4CXtHf3R4.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Mugen"}
        typeOfWork={"Design studio"}
        mainImage={{ src: "https://framerusercontent.com/images/AZe7hFsRlGAWp9spF25RMEwS0gA.jpg?width=1600&height=1200", alt: "" }}
      />
      <ProjectCardFramerComponent.Responsive
        projectLink={"/projects/:slug"}
        title={"Axiom"}
        typeOfWork={"Ecommerce Site"}
        mainImage={{ src: "https://framerusercontent.com/images/q3ruKmoVYmFXP9EeyZlQPnTDuVw.jpg?width=1600&height=1200", alt: "" }}
      />
    </div>
  )
}
